### ISSUE TITLE
急需联系

### ISSUE THREAD

**Issue by miyalee** [Fuphoenixes/vue-loading-plugin#1]
您好，我是急需联系你，请moji私我好吗

**Comment by Fuphoenixes** [comment]
什么？

**Comment by Fuphoenixes** [comment]
> 您好，我是momo的limengya急需联系你，请moji私我好吗

什么?

**Comment by miyalee** [comment]
> > 您好，我是momo的limengya急需联系你，请moji私我好吗
> 
> 什么?

不好意思有个项目贴了这个链接，我应该是找错人了

**Comment by miyalee** [comment]
麻烦删掉吧，抱歉
